name: Deploy

on:
  push:
    branches:
    - main

env:
  STACK_NAME: Sam-Cognito

jobs:
  deploy-aws:
    name: Deploy on AWS
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Validate
      run: sam validate

    - name: Build
      run: sam build

    - name: Preserve build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: .aws-sam

    - name: Deploy
      run: |
        sam deploy \
        --stack-name $STACK_NAME \
        --s3-bucket ${{ vars.S3_BUCKET }} \
        --parameter-overrides \
        LambdaAccessKeyId=${{ secrets.AWS_ACCESS_KEY_ID }} \
        LambdaSecretAccessKey=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
        LambdaRegion=${{ secrets.AWS_REGION }} \
        LambdaStageName=api
